FROM ubuntu:18.04

CMD git clone https://github.com/alex-d-tc/distributed-systems-algorithms && apt-get install go && cd ./distributed-systems-algorithms && go build && ./distributed-systems-algorithms

