version: '3'

services:
  node-1:
    image: 'distributed-systems'
    env_file:
      - ./.env
    networks:
      dist-net:
        ipv4_address: 192.168.0.2
  node-2:
    image: 'distributed-systems'
    env_file:
      - ./.env
    networks:
      dist-net:
        ipv4_address: 192.168.0.3
  node-3:
    image: 'distributed-systems'
    env_file:
      - ./.env
    networks:
      dist-net:
        ipv4_address: 192.168.0.4
  node-4:
    image: 'distributed-systems'
    env_file:
      - ./.env
    networks:
      dist-net:
        ipv4_address: 192.168.0.5

networks: 
  dist-net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "192.168.0.0/16"
