version: '3'

services:

  node-1:
    image: 'distributed-systems'
    build:
      context: ../../
      dockerfile: ./docker/node/Dockerfile
    env_file:
      - ./.env
    networks:
      dist-net:
        ipv4_address: 10.0.0.2
    ports:
      - "0.0.0.0:41000:40000"

  node-2:
    image: 'distributed-systems'
    env_file:
      - ./.env
    networks:
      dist-net:
        ipv4_address: 10.0.0.3
    ports:
      - "0.0.0.0:41001:40000"

  node-3:
    image: 'distributed-systems'
    env_file:
      - ./.env
    networks:
      dist-net:
        ipv4_address: 10.0.0.4
    ports:
      - "0.0.0.0:41002:40000"
      
  node-4:
    image: 'distributed-systems'
    env_file:
      - ./.env
    networks:
      dist-net:
        ipv4_address: 10.0.0.5
    ports:
      - "0.0.0.0:41003:40000"

networks:
  dist-net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "10.0.0.0/16"
